### ISSUE TITLE
Prism 7 WPF

### ISSUE THREAD

**Issue by datchung** [PrismLibrary/Prism-Documentation#28]
When I visit the official docs website at http://prismlibrary.github.io/docs/ I only see Prism 6 listed as legacy under WPF.

I'm new to Prism so I'm relying on the documentation. Is there a reason why Prism 7 is missing under WPF?

**Comment by brianlagunas** [comment]
Because I haven't had time to write it :).

The v6 docs are very close to v7 so you can use those docs to help you get started.

**Comment by mixonomicon** [comment]
Any chance this could happen? Especially now with bootstrapper class marked as obsolete and us starting to use `PrismApplication`, there is a lot of confusion how to do all the things that were once part of bootstrapper.

**Comment by brianlagunas** [comment]
Anything is possible. Especially if the community helps out. The API for the PrismApplication is almost identical to the Bootstrapper. Shouldn't be too difficult to convert.

**Comment by davidhenley** [comment]
Can you at least write a "How to convert to Prism 7" page so that newcomers won't be wondering what's going on with Prism 7?

**Comment by dansiegel** [comment]
@davidhenley can you please open a new issue and expand on your ask. What is it that you are struggling with? If you weren't struggling, what specifically is it that you are asking for to help a newcomer? Also remember this is Open Source we do accept PR's on the docs as long as you've got an open issue and we're on the same page with what you're proposing.

**Comment by davidhenley** [comment]
@dansiegel It seems all issues on Prism 7 documentation get closed. I would gladly help write it but I'm trying to learn best practices at the moment for Prism 7 as well.

I just hope someone more knowledgeable would write a Prism 7 one pager on the site until the full docs get updated so that "Legacy" isn't the only thing up when you go to Prism WPF.

Sorry, I don't mean to sound rude or anything. I love the project. I just think it's a good idea not to scare newcomers away with "Legacy". @brianlagunas says that "The API for the PrismApplication is almost identical to the Bootstrapper." At least a list of what has changed would be great.

Let me know what you think.

**Comment by codeputer** [comment]
Is the async interface new to v7? Learn from tests? As per my question on SO
