### ISSUE TITLE
improve docs for modularity (2 issues)

### ISSUE THREAD

**Issue by Countryen** [PrismLibrary/Prism-Documentation#98]
The current docs on the website (respectively here on github) seem to be a bit out of date. 
I am new to PRISM and have noticed a lot of small pieces that might be worth changing to help getting into PRISM.

# First: DirectoryModuleCatalog

The listed `DirectoryModuleCatalog` doesn't exist (anymore?).
I've found a [blog post from Brian Lagunas](https://brianlagunas.com/prism-dynamically-discover-and-load-modules-at-runtime/) explaining it, but I think it's out dated.
Is there any new way to achieve the same?
We are currently using MEF to do it but if there is a PRISM way that would be nice.

# Second: CreateModuleCatalog(IModuleCatalog moduleCatalog)

The method `CreateModuleCatalog(IModuleCatalog moduleCatalog)` is sometimes used instead of the (newer?) 
`ConfigureModuleCatalog(IModuleCatalog moduleCatalog)`. I can't find any method named "CreateModuleCatalog".

If preferred, I can make a PR to change that or give you exact locations (line numbers) where these are.
Any other way to improve documentation?

**Comment by brianlagunas** [comment]
You didn't specify which platform you are targeting, so I will assume WPF since yo unmentioned MEF.

There is definitely still [DirectoryModuleCatalog](https://github.com/PrismLibrary/Prism/blob/master/src/Wpf/Prism.Wpf/Modularity/DirectoryModuleCatalog.net45.cs).

`CreateModuleCatalog(IModuleCatalog moduleCatalog)` does not exist in Prism. Use `CreateModuleCatalog()` if you wish to replace the default module catalog

`ConfigureModuleCatalog(IModuleCatalog moduleCatalog)` is also definitely there as you can see [here in source](https://github.com/PrismLibrary/Prism/blob/master/src/Wpf/Prism.Wpf/PrismApplicationBase.cs#L172).

**Comment by Countryen** [comment]
Okay thank you for the quick answers. Sorry, for not specifying the target: **We use Xamarin.Forms and target Android + UWP.**
That clears my questions as I didn't think that this is due to not using WPF.
